import 'package:flutter/material.dart';

enum Language {
  en,
  id,
  es,
  zh;

  String get code {
    return name;
  }

  String get displayName {
    switch (this) {
      case Language.en:
        return 'English';
      case Language.id:
        return 'Indonesia';
      case Language.es:
        return 'Español';
      case Language.zh:
        return '中文';
    }
  }

  String getDisplayName(Language currentLanguage) {
    switch (this) {
      case Language.en:
        return currentLanguage == Language.en ? 'English' : 
               currentLanguage == Language.id ? 'Inggris' :
               currentLanguage == Language.es ? 'Inglés' :
               '英语';
      case Language.id:
        return currentLanguage == Language.en ? 'Indonesian' :
               currentLanguage == Language.id ? 'Indonesia' :
               currentLanguage == Language.es ? 'Indonesio' :
               '印尼语';
      case Language.es:
        return currentLanguage == Language.en ? 'Spanish' :
               currentLanguage == Language.id ? 'Spanyol' :
               currentLanguage == Language.es ? 'Español' :
               '西班牙语';
      case Language.zh:
        return currentLanguage == Language.en ? 'Chinese' :
               currentLanguage == Language.id ? 'Mandarin' :
               currentLanguage == Language.es ? 'Chino' :
               '中文';
    }
  }
}

class AppLocalizations {
  final Language language;

  AppLocalizations(this.language);

  String get(String key, [List<String>? args]) {
    final translations = _translations[language.code] ?? _translations['en']!;
    String text = translations[key] ?? key;
    
    if (args != null) {
      for (var i = 0; i < args.length; i++) {
        text = text.replaceAll('{$i}', args[i]);
      }
    }
    
    return text;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'BuddyBase',
      'contacts': 'Contacts',
      'favorites': 'Favorites',
      'groups': 'Groups',
      'birthdays': 'Birthdays',
      'profile': 'Profile',
      'settings': 'Settings',
      'name': 'Name',
      'phone': 'Phone',
      'email': 'Email',
      'address': 'Address',
      'notes': 'Notes',
      'group': 'Group',
      'no_group': 'No Group',
      'birthday': 'Birthday',
      'select_birthday': 'Select Birthday',
      'enable_reminder': 'Enable Birthday Reminder',
      'disable_reminder': 'Disable Birthday Reminder',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add_contact': 'Add Contact',
      'edit_contact': 'Edit Contact',
      'delete_contact': 'Delete Contact',
      'delete_contact_confirmation': 'Are you sure you want to delete {0}?',
      'not_signed_in': 'Not Signed In',
      'sign_in': 'Sign In',
      'sign_out': 'Sign Out',
      'member_since': 'Member Since',
      'not_provided': 'Not Provided',
      'not_available': 'Not Available',
      'birthday_reminders': 'Birthday Reminders',
      'no_birthday_reminders': 'No birthdays on this day',
      'birthday_today': 'Birthday today!',
      'birthday_tomorrow': 'Birthday tomorrow!',
      'birthday_in_days': 'Birthday in {days} days',
      'appearance': 'Appearance',
      'theme': 'Theme',
      'system_theme': 'System Theme',
      'light_theme': 'Light Theme',
      'dark_theme': 'Dark Theme',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'about': 'About',
      'app_version': 'App Version',
      'privacy_policy': 'Privacy Policy',
      'terms_of_service': 'Terms of Service',
      'name_required': 'Name is required',
      'search_contacts': 'Search contacts...',
      'no_contacts': 'No contacts yet',
      'no_results': 'No results found',
      'sort_az': 'A to Z',
      'sort_za': 'Z to A',
      'sort_recent': 'Recent',
      'sort_contacts': 'Sort contacts',
      'upload_progress': 'Upload progress: {0}%',
      'error_upload': 'Error uploading: {0}',
      'error_general': 'An error occurred: {0}',
      'success_profile_update': 'Profile updated successfully',
      'error_auth': 'Authentication error: {0}',
      'confirm_delete': 'Confirm Delete',
      'yes': 'Yes',
      'no': 'No',
      'no_favorites': 'No favorite contacts',
      'no_groups': 'No groups yet',
      'search_groups': 'Search groups...',
      'login': 'Login',
      'create_account': 'Create Account',
      'email_required': 'Email is required',
      'invalid_email': 'Please enter a valid email',
      'password': 'Password',
      'password_required': 'Password is required',
      'password_too_short': 'Password must be at least 6 characters',
      'group_family': 'Family',
      'group_work': 'Work',
      'group_friend': 'Friend',
      'group_other': 'Other',
      'add_to_favorites': 'Add to Favorites',
      'remove_from_favorites': 'Remove from Favorites',
      'calendar': 'Calendar',
      'select_date': 'Select Date',
      'today': 'Today',
      'upcoming_birthdays': 'Upcoming Birthdays',
      'birthday_card': 'Birthday Card',
      'send_birthday_card': 'Send Birthday Card',
      'send_email': 'Send Email',
      'send_sms': 'Send SMS',
      'no_email': 'No email address available',
      'no_phone': 'No phone number available',
      'email_error': 'Could not launch email app',
      'sms_error': 'Could not launch messaging app',
    },
    'id': {
      'app_name': 'BuddyBase',
      'contacts': 'Kontak',
      'favorites': 'Favorit',
      'groups': 'Grup',
      'birthdays': 'Ulang Tahun',
      'profile': 'Profil',
      'settings': 'Pengaturan',
      'name': 'Nama',
      'phone': 'Telepon',
      'email': 'Email',
      'address': 'Alamat',
      'notes': 'Catatan',
      'group': 'Grup',
      'no_group': 'Tidak Ada Grup',
      'birthday': 'Ulang Tahun',
      'select_birthday': 'Pilih Tanggal Ulang Tahun',
      'enable_reminder': 'Aktifkan Pengingat Ulang Tahun',
      'disable_reminder': 'Nonaktifkan Pengingat Ulang Tahun',
      'save': 'Simpan',
      'cancel': 'Batal',
      'delete': 'Hapus',
      'edit': 'Ubah',
      'add_contact': 'Tambah Kontak',
      'edit_contact': 'Ubah Kontak',
      'delete_contact': 'Hapus Kontak',
      'delete_contact_confirmation': 'Apakah Anda yakin ingin menghapus {0}?',
      'not_signed_in': 'Belum Masuk',
      'sign_in': 'Masuk',
      'sign_out': 'Keluar',
      'member_since': 'Bergabung Sejak',
      'not_provided': 'Tidak Disediakan',
      'not_available': 'Tidak Tersedia',
      'birthday_reminders': 'Pengingat Ulang Tahun',
      'no_birthday_reminders': 'Tidak ada ulang tahun hari ini',
      'birthday_today': 'Ulang tahun hari ini!',
      'birthday_tomorrow': 'Ulang tahun besok!',
      'birthday_in_days': 'Ulang tahun dalam {days} hari',
      'appearance': 'Tampilan',
      'theme': 'Tema',
      'system_theme': 'Tema Sistem',
      'light_theme': 'Tema Terang',
      'dark_theme': 'Tema Gelap',
      'dark_mode': 'Mode Gelap',
      'language': 'Bahasa',
      'about': 'Tentang',
      'app_version': 'Versi Aplikasi',
      'privacy_policy': 'Kebijakan Privasi',
      'terms_of_service': 'Ketentuan Layanan',
      'name_required': 'Nama diperlukan',
      'search_contacts': 'Cari kontak...',
      'no_contacts': 'Belum ada kontak',
      'no_results': 'Tidak ada hasil',
      'sort_az': 'A sampai Z',
      'sort_za': 'Z sampai A',
      'sort_recent': 'Terbaru',
      'sort_contacts': 'Urutkan kontak',
      'upload_progress': 'Proses unggah: {0}%',
      'error_upload': 'Gagal mengunggah: {0}',
      'error_general': 'Terjadi kesalahan: {0}',
      'success_profile_update': 'Profil berhasil diperbarui',
      'error_auth': 'Kesalahan autentikasi: {0}',
      'confirm_delete': 'Konfirmasi Hapus',
      'yes': 'Ya',
      'no': 'Tidak',
      'no_favorites': 'Belum ada kontak favorit',
      'no_groups': 'Belum ada grup',
      'search_groups': 'Cari grup...',
      'login': 'Masuk',
      'create_account': 'Buat Akun',
      'email_required': 'Email diperlukan',
      'invalid_email': 'Masukkan email yang valid',
      'password': 'Kata Sandi',
      'password_required': 'Kata sandi diperlukan',
      'password_too_short': 'Kata sandi minimal 6 karakter',
      'group_family': 'Keluarga',
      'group_work': 'Kerja',
      'group_friend': 'Teman',
      'group_other': 'Lainnya',
      'add_to_favorites': 'Tambah ke Favorit',
      'remove_from_favorites': 'Hapus dari Favorit',
      'calendar': 'Kalender',
      'select_date': 'Pilih Tanggal',
      'today': 'Hari Ini',
      'upcoming_birthdays': 'Ulang Tahun Mendatang',
      'birthday_card': 'Kartu Ulang Tahun',
      'send_birthday_card': 'Kirim Kartu Ulang Tahun',
      'send_email': 'Kirim Email',
      'send_sms': 'Kirim SMS',
      'no_email': 'Tidak ada alamat email',
      'no_phone': 'Tidak ada nomor telepon',
      'email_error': 'Tidak dapat membuka aplikasi email',
      'sms_error': 'Tidak dapat membuka aplikasi pesan',
    },
    'es': {
      'app_name': 'BuddyBase',
      'contacts': 'Contactos',
      'favorites': 'Favoritos',
      'groups': 'Grupos',
      'birthdays': 'Cumpleaños',
      'profile': 'Perfil',
      'settings': 'Ajustes',
      'name': 'Nombre',
      'phone': 'Teléfono',
      'email': 'Correo',
      'address': 'Dirección',
      'notes': 'Notas',
      'group': 'Grupo',
      'no_group': 'Sin Grupo',
      'birthday': 'Cumpleaños',
      'select_birthday': 'Seleccionar Cumpleaños',
      'enable_reminder': 'Activar Recordatorio',
      'disable_reminder': 'Desactivar Recordatorio',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'add_contact': 'Añadir Contacto',
      'edit_contact': 'Editar Contacto',
      'delete_contact': 'Eliminar Contacto',
      'delete_contact_confirmation': '¿Estás seguro de que quieres eliminar a {0}?',
      'not_signed_in': 'No has iniciado sesión',
      'sign_in': 'Iniciar Sesión',
      'sign_out': 'Cerrar Sesión',
      'member_since': 'Miembro desde',
      'not_provided': 'No proporcionado',
      'not_available': 'No disponible',
      'birthday_reminders': 'Recordatorios de Cumpleaños',
      'no_birthday_reminders': 'No hay cumpleaños hoy',
      'birthday_today': '¡Cumpleaños hoy!',
      'birthday_tomorrow': '¡Cumpleaños mañana!',
      'birthday_in_days': 'Cumpleaños en {days} días',
      'appearance': 'Apariencia',
      'theme': 'Tema',
      'system_theme': 'Tema del Sistema',
      'light_theme': 'Tema Claro',
      'dark_theme': 'Tema Oscuro',
      'dark_mode': 'Modo Oscuro',
      'language': 'Idioma',
      'about': 'Acerca de',
      'app_version': 'Versión de la App',
      'privacy_policy': 'Política de Privacidad',
      'terms_of_service': 'Términos de Servicio',
      'name_required': 'El nombre es requerido',
      'search_contacts': 'Buscar contactos...',
      'no_contacts': 'No hay contactos aún',
      'no_results': 'No se encontraron resultados',
      'sort_az': 'A a Z',
      'sort_za': 'Z a A',
      'sort_recent': 'Recientes',
      'sort_contacts': 'Ordenar contactos',
      'upload_progress': 'Progreso de carga: {0}%',
      'error_upload': 'Error al cargar: {0}',
      'error_general': 'Ocurrió un error: {0}',
      'success_profile_update': 'Perfil actualizado exitosamente',
      'error_auth': 'Error de autenticación: {0}',
      'confirm_delete': 'Confirmar Eliminación',
      'yes': 'Sí',
      'no': 'No',
      'no_favorites': 'No hay contactos favoritos',
      'no_groups': 'No hay grupos aún',
      'search_groups': 'Buscar grupos...',
      'login': 'Iniciar Sesión',
      'create_account': 'Crear Cuenta',
      'email_required': 'El correo es requerido',
      'invalid_email': 'Ingresa un correo válido',
      'password': 'Contraseña',
      'password_required': 'La contraseña es requerida',
      'password_too_short': 'La contraseña debe tener al menos 6 caracteres',
      'group_family': 'Familia',
      'group_work': 'Trabajo',
      'group_friend': 'Amigo',
      'group_other': 'Otro',
      'add_to_favorites': 'Añadir a Favoritos',
      'remove_from_favorites': 'Quitar de Favoritos',
      'calendar': 'Calendario',
      'select_date': 'Seleccionar Fecha',
      'today': 'Hoy',
      'upcoming_birthdays': 'Próximos Cumpleaños',
      'birthday_card': 'Tarjeta de Cumpleaños',
      'send_birthday_card': 'Enviar Tarjeta de Cumpleaños',
      'send_email': 'Enviar Correo',
      'send_sms': 'Enviar SMS',
      'no_email': 'No hay dirección de correo disponible',
      'no_phone': 'No hay número de teléfono disponible',
      'email_error': 'No se pudo abrir la aplicación de correo',
      'sms_error': 'No se pudo abrir la aplicación de mensajes',
    },
    'zh': {
      'app_name': 'BuddyBase',
      'contacts': '联系人',
      'favorites': '收藏夹',
      'groups': '分组',
      'birthdays': '生日',
      'profile': '个人资料',
      'settings': '设置',
      'name': '姓名',
      'phone': '电话',
      'email': '邮箱',
      'address': '地址',
      'notes': '备注',
      'group': '分组',
      'no_group': '无分组',
      'birthday': '生日',
      'select_birthday': '选择生日',
      'enable_reminder': '开启生日提醒',
      'disable_reminder': '关闭生日提醒',
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'add_contact': '添加联系人',
      'edit_contact': '编辑联系人',
      'delete_contact': '删除联系人',
      'delete_contact_confirmation': '确定要删除 {0} 吗？',
      'not_signed_in': '未登录',
      'sign_in': '登录',
      'sign_out': '退出登录',
      'member_since': '注册时间',
      'not_provided': '未提供',
      'not_available': '不可用',
      'birthday_reminders': '生日提醒',
      'no_birthday_reminders': '今天没有生日',
      'birthday_today': '今天生日！',
      'birthday_tomorrow': '明天生日！',
      'birthday_in_days': '{days}天后生日',
      'appearance': '外观',
      'theme': '主题',
      'system_theme': '系统主题',
      'light_theme': '浅色主题',
      'dark_theme': '深色主题',
      'dark_mode': '深色模式',
      'language': '语言',
      'about': '关于',
      'app_version': '应用版本',
      'privacy_policy': '隐私政策',
      'terms_of_service': '服务条款',
      'name_required': '请输入姓名',
      'search_contacts': '搜索联系人...',
      'no_contacts': '暂无联系人',
      'no_results': '未找到结果',
      'sort_az': 'A 到 Z',
      'sort_za': 'Z 到 A',
      'sort_recent': '最近',
      'sort_contacts': '排序联系人',
      'upload_progress': '上传进度：{0}%',
      'error_upload': '上传错误：{0}',
      'error_general': '发生错误：{0}',
      'success_profile_update': '个人资料更新成功',
      'error_auth': '认证错误：{0}',
      'confirm_delete': '确认删除',
      'yes': '是',
      'no': '否',
      'no_favorites': '暂无收藏联系人',
      'no_groups': '暂无分组',
      'search_groups': '搜索分组...',
      'login': '登录',
      'create_account': '创建账号',
      'email_required': '请输入邮箱',
      'invalid_email': '请输入有效的邮箱',
      'password': '密码',
      'password_required': '请输入密码',
      'password_too_short': '密码至少需要6个字符',
      'group_family': '家人',
      'group_work': '工作',
      'group_friend': '朋友',
      'group_other': '其他',
      'add_to_favorites': '添加到收藏',
      'remove_from_favorites': '从收藏中移除',
      'calendar': '日历',
      'select_date': '选择日期',
      'today': '今天',
      'upcoming_birthdays': '即将到来的生日',
      'birthday_card': '生日贺卡',
      'send_birthday_card': '发送生日贺卡',
      'send_email': '发送邮件',
      'send_sms': '发送短信',
      'no_email': '无可用邮箱地址',
      'no_phone': '无可用电话号码',
      'email_error': '无法打开邮件应用',
      'sms_error': '无法打开短信应用',
    },
  };
} 